// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

package pd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StudentInfoRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32   `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentInfoRequest) Reset()         { *m = StudentInfoRequest{} }
func (m *StudentInfoRequest) String() string { return proto.CompactTextString(m) }
func (*StudentInfoRequest) ProtoMessage()    {}
func (*StudentInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_student_ea7f2158532e13dd, []int{0}
}
func (m *StudentInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentInfoRequest.Unmarshal(m, b)
}
func (m *StudentInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentInfoRequest.Marshal(b, m, deterministic)
}
func (dst *StudentInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentInfoRequest.Merge(dst, src)
}
func (m *StudentInfoRequest) XXX_Size() int {
	return xxx_messageInfo_StudentInfoRequest.Size(m)
}
func (m *StudentInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StudentInfoRequest proto.InternalMessageInfo

func (m *StudentInfoRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StudentInfoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudentInfoRequest) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type StudentInfoResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32   `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentInfoResponse) Reset()         { *m = StudentInfoResponse{} }
func (m *StudentInfoResponse) String() string { return proto.CompactTextString(m) }
func (*StudentInfoResponse) ProtoMessage()    {}
func (*StudentInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_student_ea7f2158532e13dd, []int{1}
}
func (m *StudentInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentInfoResponse.Unmarshal(m, b)
}
func (m *StudentInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentInfoResponse.Marshal(b, m, deterministic)
}
func (dst *StudentInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentInfoResponse.Merge(dst, src)
}
func (m *StudentInfoResponse) XXX_Size() int {
	return xxx_messageInfo_StudentInfoResponse.Size(m)
}
func (m *StudentInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StudentInfoResponse proto.InternalMessageInfo

func (m *StudentInfoResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StudentInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudentInfoResponse) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*StudentInfoRequest)(nil), "pd.StudentInfoRequest")
	proto.RegisterType((*StudentInfoResponse)(nil), "pd.StudentInfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StudentInfoClient is the client API for StudentInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentInfoClient interface {
	GetStudentInfo(ctx context.Context, in *StudentInfoRequest, opts ...grpc.CallOption) (*StudentInfoResponse, error)
	UpdateStudentInfo(ctx context.Context, opts ...grpc.CallOption) (StudentInfo_UpdateStudentInfoClient, error)
}

type studentInfoClient struct {
	cc *grpc.ClientConn
}

func NewStudentInfoClient(cc *grpc.ClientConn) StudentInfoClient {
	return &studentInfoClient{cc}
}

func (c *studentInfoClient) GetStudentInfo(ctx context.Context, in *StudentInfoRequest, opts ...grpc.CallOption) (*StudentInfoResponse, error) {
	out := new(StudentInfoResponse)
	err := c.cc.Invoke(ctx, "/pd.StudentInfo/GetStudentInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentInfoClient) UpdateStudentInfo(ctx context.Context, opts ...grpc.CallOption) (StudentInfo_UpdateStudentInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StudentInfo_serviceDesc.Streams[0], "/pd.StudentInfo/UpdateStudentInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &studentInfoUpdateStudentInfoClient{stream}
	return x, nil
}

type StudentInfo_UpdateStudentInfoClient interface {
	Send(*StudentInfoRequest) error
	Recv() (*StudentInfoResponse, error)
	grpc.ClientStream
}

type studentInfoUpdateStudentInfoClient struct {
	grpc.ClientStream
}

func (x *studentInfoUpdateStudentInfoClient) Send(m *StudentInfoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *studentInfoUpdateStudentInfoClient) Recv() (*StudentInfoResponse, error) {
	m := new(StudentInfoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StudentInfoServer is the server API for StudentInfo service.
type StudentInfoServer interface {
	GetStudentInfo(context.Context, *StudentInfoRequest) (*StudentInfoResponse, error)
	UpdateStudentInfo(StudentInfo_UpdateStudentInfoServer) error
}

func RegisterStudentInfoServer(s *grpc.Server, srv StudentInfoServer) {
	s.RegisterService(&_StudentInfo_serviceDesc, srv)
}

func _StudentInfo_GetStudentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentInfoServer).GetStudentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pd.StudentInfo/GetStudentInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentInfoServer).GetStudentInfo(ctx, req.(*StudentInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentInfo_UpdateStudentInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StudentInfoServer).UpdateStudentInfo(&studentInfoUpdateStudentInfoServer{stream})
}

type StudentInfo_UpdateStudentInfoServer interface {
	Send(*StudentInfoResponse) error
	Recv() (*StudentInfoRequest, error)
	grpc.ServerStream
}

type studentInfoUpdateStudentInfoServer struct {
	grpc.ServerStream
}

func (x *studentInfoUpdateStudentInfoServer) Send(m *StudentInfoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *studentInfoUpdateStudentInfoServer) Recv() (*StudentInfoRequest, error) {
	m := new(StudentInfoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _StudentInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pd.StudentInfo",
	HandlerType: (*StudentInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentInfo",
			Handler:    _StudentInfo_GetStudentInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateStudentInfo",
			Handler:       _StudentInfo_UpdateStudentInfo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "student.proto",
}

func init() { proto.RegisterFile("student.proto", fileDescriptor_student_ea7f2158532e13dd) }

var fileDescriptor_student_ea7f2158532e13dd = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x29, 0x4d,
	0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x51, 0xf2, 0xe2,
	0x12, 0x0a, 0x86, 0x08, 0x7a, 0xe6, 0xa5, 0xe5, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x31, 0x65, 0xa6, 0x08,
	0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x42, 0x02, 0x5c, 0xcc, 0x89, 0xe9, 0xa9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x20, 0xa6,
	0x92, 0x37, 0x97, 0x30, 0x8a, 0x59, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0xe4, 0x19, 0x66, 0x34,
	0x8f, 0x91, 0x8b, 0x1b, 0xc9, 0x34, 0x21, 0x67, 0x2e, 0x3e, 0xf7, 0xd4, 0x12, 0x64, 0x11, 0x31,
	0xbd, 0x82, 0x14, 0x3d, 0x4c, 0xc7, 0x4b, 0x89, 0x63, 0x88, 0x43, 0x1c, 0xa2, 0xc4, 0x20, 0xe4,
	0xc5, 0x25, 0x18, 0x5a, 0x90, 0x92, 0x58, 0x92, 0x4a, 0x99, 0x39, 0x1a, 0x8c, 0x06, 0x8c, 0x49,
	0x6c, 0xe0, 0x40, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xfc, 0xb6, 0xea, 0x55, 0x01,
	0x00, 0x00,
}
